server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: profile_skills_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/skills/**
          filters:
            - StripPrefix=2
        - id: profile_ai_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/api/**
          filters:
            - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: file_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2
        - id: chat_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2
        - id: assignment_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/assignment/**
          filters:
            - StripPrefix=2
        - id: workload_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/workload/**
          filters:
            - StripPrefix=2
        - id: task_service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/task/**
          filters:
            - StripPrefix=2
        - id: ai_service
          uri: http://localhost:8089
          predicates:
            - Path=${app.api-prefix}/ai/**
          filters:
            - StripPrefix=2
        - id: project_service
          uri: http://localhost:8090
          predicates:
            - Path=${app.api-prefix}/project/**
          filters:
            - StripPrefix=2