server:
  port: 8085
  servlet:
    context-path: /chat
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat-service
      auto-index-creation: true
app:
  services:
    profile:
      url: http://localhost:8081/profile
    identity:
      url: http://localhost:8080/identity
    notification:
      url: http://localhost:8082/notification