package com.mnp.task.enums;

public enum SkillType {
    // Skill Categories
    PROGRAMMING_LANGUAGE,
    FRAMEWORK,
    DATABASE,
    CLOUD_PLATFORM,
    DEVELOPMENT_TOOL,
    TESTING_TOOL,
    ARCHITECTURE,
    SECURITY,
    MOBILE_DEVELOPMENT,
    DATA_ANALYSIS,
    PROJECT_MANAGEMENT,
    SOFT_SKILL,
    FRONTEND_TECHNOLOGY,
    BACKEND_TECHNOLOGY,
    DEVOPS_TOOL,
    API_TECHNOLOGY,
    PERFORMANCE_OPTIMIZATION,
    VERSION_CONTROL,
    BUILD_TOOL,
    MONITORING_TOOL
}
